/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javamysql.ui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javamysql.database.ICRUDImpl;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nikolas
 */
public class CandidateProject extends javax.swing.JFrame {
    
    ICRUDImpl iCRUDImpl = new ICRUDImpl();
    CandidateUI candidateUI = new CandidateUI();
    
    private static String valueCandidateUsername = null;
    private static int valueProjectNumber = 0;

    /**
     * Creates new form CandidateProject
     */
    public CandidateProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProjects = new javax.swing.JTable();
        ButtonBack = new javax.swing.JButton();
        ButtonAddANewProject = new javax.swing.JButton();
        ButtonDeleteAProject = new javax.swing.JButton();
        ButtonEditAProject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Projects");

        TableProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableProjects.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TableProjectsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TableProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProjectsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableProjects);

        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        ButtonAddANewProject.setText("Add a new Project");
        ButtonAddANewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddANewProjectActionPerformed(evt);
            }
        });

        ButtonDeleteAProject.setText("Delete a Project");
        ButtonDeleteAProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteAProjectActionPerformed(evt);
            }
        });

        ButtonEditAProject.setText("Edit a Project");
        ButtonEditAProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditAProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonEditAProject)
                        .addGap(108, 108, 108)
                        .addComponent(ButtonAddANewProject)
                        .addGap(156, 156, 156)
                        .addComponent(ButtonDeleteAProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(ButtonBack)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonBack)
                    .addComponent(ButtonAddANewProject)
                    .addComponent(ButtonDeleteAProject)
                    .addComponent(ButtonEditAProject))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void TableProjectsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TableProjectsAncestorAdded
        getCandidateProject(candidateUI.getNewUsername());
    }//GEN-LAST:event_TableProjectsAncestorAdded

    private void TableProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProjectsMouseClicked
        int row = TableProjects.getSelectedRow();
        TableModel model = TableProjects.getModel();
        setValueCandidateUsername(TableProjects.getModel().getValueAt(row, 0).toString());
        setValueProjectNumber(Integer.parseInt(model.getValueAt(row, 1).toString()));
    }//GEN-LAST:event_TableProjectsMouseClicked

    private void ButtonDeleteAProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteAProjectActionPerformed
        iCRUDImpl.delCandidateProject(getValueCandidateUsername(), getValueProjectNumber());
    }//GEN-LAST:event_ButtonDeleteAProjectActionPerformed

    private void ButtonAddANewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddANewProjectActionPerformed
        CandidateAddANewProject candidateAddANewProject = new CandidateAddANewProject();
        candidateAddANewProject.setVisible(true);
    }//GEN-LAST:event_ButtonAddANewProjectActionPerformed

    private void ButtonEditAProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditAProjectActionPerformed
        CandidateEditAProject candidateEditAProject = new CandidateEditAProject();
        candidateEditAProject.setVisible(true);
    }//GEN-LAST:event_ButtonEditAProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandidateProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddANewProject;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonDeleteAProject;
    private javax.swing.JButton ButtonEditAProject;
    private javax.swing.JTable TableProjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


    public CandidateProject getCandidateProject(String candidateUsername) {
        iCRUDImpl.openConnection();
        try{
            CandidateProject candidateProject = new CandidateProject();
            String query = "SELECT * FROM project WHERE candid = '" + candidateUsername + "'";
            PreparedStatement preparedStatement = iCRUDImpl.getConnection().prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();
            TableProjects.setModel(DbUtils.resultSetToTableModel(resultSet));
            return candidateProject;
        } catch (SQLException e) {
            return null;
        }
    }
    
    
    /**
     * @return the valueCandidateUsername
     */
    public String getValueCandidateUsername() {
        return valueCandidateUsername;
    }

    /**
     * @param valueCandidateUsername the valueCandidateUsername to set
     */
    public void setValueCandidateUsername(String valueCandidateUsername) {
        CandidateProject.valueCandidateUsername = valueCandidateUsername;
    }

    /**
     * @return the valueProjectNumber
     */
    public int getValueProjectNumber() {
        return valueProjectNumber;
    }

    /**
     * @param valueProjectNumber the valueProjectNumber to set
     */
    public void setValueProjectNumber(int valueProjectNumber) {
        CandidateProject.valueProjectNumber = valueProjectNumber;
    }
    
}
