/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javamysql.ui;

import javamysql.database.ICRUDImpl;
import javamysql.model.Company;
import javamysql.model.Recruiter;

/**
 *
 * @author Nikolas
 */
public class CompanyUI extends javax.swing.JFrame {

    /**
     * @return the changeAFM
     */
    public javax.swing.JTextField getChangeAFM() {
        return changeAFM;
    }

    /**
     * @param changeAFM the changeAFM to set
     */
    public void setChangeAFM(javax.swing.JTextField changeAFM) {
        this.changeAFM = changeAFM;
    }
    
    int counter = 0;
    
    private static String newStreet, newCity, newCountry;
    private static int newTelephone, newNumber;
    
    ICRUDImpl iCRUDImpl = new ICRUDImpl();
    Recruiter recruiter = new Recruiter();
    Company company = new Company();
    
    protected String intToStringAFM = Integer.toString(company.getAFM());
    protected String intToStringTelephone = Integer.toString(company.getTelephone());
    protected String intToStringNumber = Integer.toString(company.getNumber());

    /**
     * Creates new form CompanyUI
     */
    public CompanyUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        changeAFM = new javax.swing.JTextField();
        City = new javax.swing.JLabel();
        DOY = new javax.swing.JLabel();
        changeCity = new javax.swing.JTextField();
        changeDOY = new javax.swing.JTextField();
        changeCountry = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        Country = new javax.swing.JLabel();
        changeName = new javax.swing.JTextField();
        Telephone = new javax.swing.JLabel();
        ButtonEditAndSave = new javax.swing.JButton();
        changeTelephone = new javax.swing.JTextField();
        Street = new javax.swing.JLabel();
        changeStreet = new javax.swing.JTextField();
        CompanyName = new javax.swing.JLabel();
        Number = new javax.swing.JLabel();
        AFM = new javax.swing.JLabel();
        changeNumber = new javax.swing.JTextField();
        ButtonBack = new javax.swing.JButton();
        ButtonOpenNewPosition = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        changeAFM.setEditable(false);
        changeAFM.setText(intToStringAFM);

        City.setText("City");

        DOY.setText("DOY");

        changeCity.setEditable(false);
        changeCity.setText(iCRUDImpl.getCompany(recruiter.getFirm()).getCity());

        changeDOY.setEditable(false);
        changeDOY.setText(iCRUDImpl.getCompany(recruiter.getFirm()).getDOY());

        changeCountry.setEditable(false);
        changeCountry.setText(iCRUDImpl.getCompany(recruiter.getFirm()).getCountry());

        Name.setText("Name");

        Country.setText("Country");

        changeName.setEditable(false);
        changeName.setText(iCRUDImpl.getCompany(recruiter.getFirm()).getName());

        Telephone.setText("Telephone");

        ButtonEditAndSave.setText("Edit");
        ButtonEditAndSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditAndSaveActionPerformed(evt);
            }
        });

        changeTelephone.setEditable(false);
        changeTelephone.setText(intToStringTelephone);

        Street.setText("Street");

        changeStreet.setEditable(false);
        changeStreet.setText(iCRUDImpl.getCompany(recruiter.getFirm()).getStreet());

        CompanyName.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        CompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompanyName.setText(iCRUDImpl.getCompany(recruiter.getFirm()).getName());

        Number.setText("Number");

        AFM.setText("AFM");

        changeNumber.setEditable(false);
        changeNumber.setText(intToStringNumber);

        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        ButtonOpenNewPosition.setText("Open New Position");
        ButtonOpenNewPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpenNewPositionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DOY, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeDOY, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AFM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeAFM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(changeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(changeCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Street, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(changeStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(changeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonEditAndSave, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(ButtonOpenNewPosition)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(ButtonBack)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AFM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeAFM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeDOY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Street, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(changeName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonEditAndSave)
                    .addComponent(ButtonOpenNewPosition))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        RecruiterUI recruiterUI = new RecruiterUI();
        recruiterUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonEditAndSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditAndSaveActionPerformed
        counter++;
        if(counter%2 == 1){
            changeTelephone.setEditable(true);
            changeStreet.setEditable(true);
            changeNumber.setEditable(true);
            changeCity.setEditable(true);
            changeCountry.setEditable(true);
            ButtonEditAndSave.setText("Save");
        } else {
            changeTelephone.setEditable(false);
            changeStreet.setEditable(false);
            changeNumber.setEditable(false);
            changeCity.setEditable(false);
            changeCountry.setEditable(false);
            ButtonEditAndSave.setText("Edit");
            // int stringToIntTelephone = Integer.parseInt(this.intToStringTelephone);
            intToStringTelephone = changeTelephone.getText();
            newTelephone = Integer.parseInt(intToStringTelephone);
            newStreet = changeStreet.getText();
            intToStringNumber = changeNumber.getText();
            newNumber = Integer.parseInt(intToStringNumber);
            newCity = changeCity.getText();
            newCountry = changeCountry.getText();
            int stringToIntAFM = Integer.parseInt(intToStringAFM);
            iCRUDImpl.getCompanyUI(stringToIntAFM);
        }
    }//GEN-LAST:event_ButtonEditAndSaveActionPerformed

    private void ButtonOpenNewPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpenNewPositionActionPerformed
        RecruiterNewPosition recruiterNewPosition = new RecruiterNewPosition();
        recruiterNewPosition.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonOpenNewPositionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AFM;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonEditAndSave;
    private javax.swing.JButton ButtonOpenNewPosition;
    private javax.swing.JLabel City;
    private javax.swing.JLabel CompanyName;
    private javax.swing.JLabel Country;
    private javax.swing.JLabel DOY;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Number;
    private javax.swing.JLabel Street;
    private javax.swing.JLabel Telephone;
    private javax.swing.JTextField changeAFM;
    private javax.swing.JTextField changeCity;
    private javax.swing.JTextField changeCountry;
    private javax.swing.JTextField changeDOY;
    private javax.swing.JTextField changeName;
    private javax.swing.JTextField changeNumber;
    private javax.swing.JTextField changeStreet;
    private javax.swing.JTextField changeTelephone;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the newTelephone
     */
    public int getNewTelephone() {
        return newTelephone;
    }

    /**
     * @param newTelephone the newTelephone to set
     */
    public void setNewTelephone(int newTelephone) {
        CompanyUI.newTelephone = newTelephone;
    }

    /**
     * @return the newStreet
     */
    public String getNewStreet() {
        return newStreet;
    }

    /**
     * @param newStreet the newStreet to set
     */
    public void setNewStreet(String newStreet) {
        CompanyUI.newStreet = newStreet;
    }

    /**
     * @return the newNumber
     */
    public int getNewNumber() {
        return newNumber;
    }

    /**
     * @param newNumber the newNumber to set
     */
    public void setNewNumber(int newNumber) {
        CompanyUI.newNumber = newNumber;
    }

    /**
     * @return the newCity
     */
    public String getNewCity() {
        return newCity;
    }

    /**
     * @param newCity the newCity to set
     */
    public void setNewCity(String newCity) {
        CompanyUI.newCity = newCity;
    }

    /**
     * @return the newCountry
     */
    public String getNewCountry() {
        return newCountry;
    }

    /**
     * @param newCountry the newCountry to set
     */
    public void setNewCountry(String newCountry) {
        CompanyUI.newCountry = newCountry;
    }
}
