/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javamysql.ui;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javamysql.database.ICRUDImpl;
import javamysql.model.Recruiter;

/**
 *
 * @author Nikolas
 */
public class RecruiterAddAJob extends javax.swing.JFrame {
    
    ICRUDImpl iCRUDImpl = new ICRUDImpl();
    
    SimpleDateFormat dateFormatTimestamp = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    DateFormat dateFormatDate = new SimpleDateFormat("yyyy-MM-dd");
    
    private static String newPosition, newSeat, newRequires;
    private static int newSalary;
    // private static Timestamp newAnnounceDate;
    // private static Date newStartDate, newSubmissionDate;
    private static java.util.Date newStartDate, newAnnounceDate, newSubmissionDate, newLastInterviewDate;
    
    protected int stringToIntSalary;
    // Date stringToDateStartDate;
    
    RecruiterUI recruiterUI = new RecruiterUI();
    Recruiter recruiter = new Recruiter();
    
    private static String[] fillComboBox;
    // String[] array = getFillComboBox().toArray(new String[getFillComboBox().size()]);

    /**
     * Creates new form AddAJob
     */
    public RecruiterAddAJob() {
        initComponents();
        updateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        changeID = new javax.swing.JTextField();
        StartDate = new javax.swing.JLabel();
        changeStartDate = new javax.swing.JTextField();
        Salary = new javax.swing.JLabel();
        changeSalary = new javax.swing.JTextField();
        changePosition = new javax.swing.JTextField();
        Position = new javax.swing.JLabel();
        Seat = new javax.swing.JLabel();
        changeSeat = new javax.swing.JTextField();
        Recruiter = new javax.swing.JLabel();
        changeRecruiter = new javax.swing.JTextField();
        AnnounceDate = new javax.swing.JLabel();
        changeAnnounceDate = new javax.swing.JTextField();
        SubmissionDate = new javax.swing.JLabel();
        changeSubmissionDate = new javax.swing.JTextField();
        ButtonAdd = new javax.swing.JButton();
        ButtonDismiss = new javax.swing.JButton();
        Seat1 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        LastInterviewDate = new javax.swing.JLabel();
        changeLastInterviewDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Format: yyyy-MM-dd");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NEW JOB");

        ID.setText("ID");

        changeID.setEditable(false);
        int stringToIntCount = Integer.parseInt(iCRUDImpl.getCountJob()) + 1;
        String intToStringCount = Integer.toString(stringToIntCount);
        System.out.println(intToStringCount);
        changeID.setText(intToStringCount);

        StartDate.setText("Start Date");

        Salary.setText("Salary");

        Position.setText("Position");

        Seat.setText("Seat");

        Recruiter.setText("Recruiter");

        changeRecruiter.setEditable(false);
        changeRecruiter.setText(recruiter.getUsername());

        AnnounceDate.setText("Annaounce Date");

        changeAnnounceDate.setEditable(false);
        String dateToStringAnnounceDate = dateFormatDate.format(System.currentTimeMillis());
        changeAnnounceDate.setText(dateToStringAnnounceDate);

        SubmissionDate.setText("Submission Date");

        ButtonAdd.setText("Add");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        ButtonDismiss.setText("Dismiss");
        ButtonDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDismissActionPerformed(evt);
            }
        });

        Seat1.setText("Requires");

        LastInterviewDate.setText("Last Interview Date");

        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Format: yyyy-MM-dd");

        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Format: yyyy-MM-dd");

        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Format: yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(changeID))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(changeStartDate))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(changeSalary))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(changePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(ButtonAdd)
                        .addGap(263, 263, 263)
                        .addComponent(ButtonDismiss)
                        .addGap(257, 257, 257))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Recruiter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(changeRecruiter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(AnnounceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(changeAnnounceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(SubmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(changeSubmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Seat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(changeSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LastInterviewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(changeLastInterviewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Seat1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastInterviewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeLastInterviewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(changeID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Seat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(changeSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Seat1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Recruiter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeRecruiter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnnounceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeAnnounceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeSubmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAdd)
                    .addComponent(ButtonDismiss))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        try {
            newStartDate = dateFormatDate.parse(changeStartDate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(RecruiterAddAJob.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date sqlNewStartDate = new java.sql.Date(newStartDate.getTime());
        setNewStartDate(sqlNewStartDate);
        
        stringToIntSalary = Integer.parseInt(changeSalary.getText());
        setNewSalary(stringToIntSalary);
        setNewPosition(changePosition.getText());
        setNewRequires((String) comboBox.getSelectedItem());
        setNewSeat(changeSeat.getText());
        
        try {
            newAnnounceDate = dateFormatDate.parse(changeAnnounceDate.getText()); 
        } catch (ParseException ex) {
            Logger.getLogger(RecruiterAddAJob.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date sqlNewAnnounceDate = new java.sql.Date(newAnnounceDate.getTime());
        setNewAnnounceDate(sqlNewAnnounceDate);
        
        try {
            newSubmissionDate = dateFormatDate.parse(changeSubmissionDate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(RecruiterAddAJob.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date sqlNewSubmissionDate = new java.sql.Date(newSubmissionDate.getTime());
        setNewSubmissionDate(sqlNewSubmissionDate);
        
        try {
            newLastInterviewDate = dateFormatDate.parse(changeLastInterviewDate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(RecruiterAddAJob.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date sqlNewLastInterviewDate = new java.sql.Date(newLastInterviewDate.getTime());
        setNewLastInterviewDate(sqlNewLastInterviewDate);
        
        int stringToIntCount = Integer.parseInt(iCRUDImpl.getCountJob());
        iCRUDImpl.newJob(stringToIntCount + 1, recruiter.getUsername());
        
        this.dispose();
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonDismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDismissActionPerformed
        this.dispose();
        dateFormatDate.format(System.currentTimeMillis());
    }//GEN-LAST:event_ButtonDismissActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecruiterAddAJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecruiterAddAJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecruiterAddAJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecruiterAddAJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecruiterAddAJob().setVisible(true);
            }
        });
        //AddAJob addAJob = new AddAJob();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnnounceDate;
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonDismiss;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel LastInterviewDate;
    private javax.swing.JLabel Position;
    private javax.swing.JLabel Recruiter;
    private javax.swing.JLabel Salary;
    private javax.swing.JLabel Seat;
    private javax.swing.JLabel Seat1;
    private javax.swing.JLabel StartDate;
    private javax.swing.JLabel SubmissionDate;
    private javax.swing.JTextField changeAnnounceDate;
    private javax.swing.JTextField changeID;
    private javax.swing.JTextField changeLastInterviewDate;
    private javax.swing.JTextField changePosition;
    private javax.swing.JTextField changeRecruiter;
    private javax.swing.JTextField changeSalary;
    private javax.swing.JTextField changeSeat;
    private javax.swing.JTextField changeStartDate;
    private javax.swing.JTextField changeSubmissionDate;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    
    private void updateComboBox(){
        iCRUDImpl.openConnection();
        String query = "SELECT * FROM antikeim";
        try {
            PreparedStatement preparedStatement = iCRUDImpl.getConnection().prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();
            while(resultSet.next()){
                comboBox.addItem(resultSet.getString("title"));
            }
        } catch (SQLException e) {
        }
    }
    
    
    /**
     * @return the newPosition
     */
    public String getNewPosition() {
        return newPosition;
    }

    /**
     * @param newPosition the newPosition to set
     */
    public void setNewPosition(String newPosition) {
        RecruiterAddAJob.newPosition = newPosition;
    }

    /**
     * @return the newSeat
     */
    public String getNewSeat() {
        return newSeat;
    }

    /**
     * @param newSeat the newSeat to set
     */
    public void setNewSeat(String newSeat) {
        RecruiterAddAJob.newSeat = newSeat;
    }
    
    /**
     * @return the newRequires
     */
    public String getNewRequires() {
        return newRequires;
    }

    /**
     * @param newRequires the newSeat to set
     */
    public void setNewRequires(String newRequires) {
        RecruiterAddAJob.newRequires = newRequires;
    }

    /**
     * @return the newSalary
     */
    public int getNewSalary() {
        return newSalary;
    }

    /**
     * @param newSalary the newSalary to set
     */
    public void setNewSalary(int newSalary) {
        RecruiterAddAJob.newSalary = newSalary;
    }

    /**
     * @param newSubmissionDate the newSubmissionDate to set
     */
    public void setNewSubmissionDate(Date newSubmissionDate) {
        RecruiterAddAJob.newSubmissionDate = newSubmissionDate;
    }
    
    public java.util.Date getNewSubmissionDate() {
        return newSubmissionDate;
    }

    private void setNewAnnounceDate(Date newAnnounceDate) {
        RecruiterAddAJob.newAnnounceDate = newAnnounceDate;
    }
    
    public java.util.Date getNewAnnounceDate() {
        return newAnnounceDate;
    }

    private void setNewStartDate(Date newStartDate) {
        RecruiterAddAJob.newStartDate = newStartDate;
    }
    
    public java.util.Date getNewStartDate() {
        return newStartDate;
    }

    /**
     * @return the fillComboBox
     */
    public String[] getFillComboBox() {
        return fillComboBox;
    }

    /**
     * @param fillComboBox the fillComboBox to set
     */
    public void setFillComboBox(String[] fillComboBox) {
        RecruiterAddAJob.fillComboBox = fillComboBox;
    }
    
    /**
     * @return the newLastInterviewDate
     */
    public java.util.Date getNewLastInterviewDate() {
        return newLastInterviewDate;
    }

    /**
     * @param newLastInterviewDate the newLastInterviewDate to set
     */
    public void setNewLastInterviewDate(java.util.Date newLastInterviewDate) {
        RecruiterAddAJob.newLastInterviewDate = newLastInterviewDate;
    }
    
}
